### ISSUE TITLE
How can I compare with integers?

### ISSUE THREAD

**Issue by MartinThoma** [mechatroner/RBQL#9]
I tried

> SELECT a3, a11 WHERE a11 > '10'

But then I also get results where a11 = 2.

What I would like to do:

> SELECT a3, a11 WHERE int(a11) > '10'

**Comment by mechatroner** [comment]
Hi @MartinThoma 
If you use Python backend, then:
`SELECT a3, a11 WHERE int(a11) > 10`
for JavaScript backend:
`SELECT a3, a11 WHERE parseInt(a11) > 10`
Basically you don't need to quote 10 just like you don't do it for number comparison in Python or JS code.

BTW for JS you can also use less explicit expression:
`SELECT a3, a11 WHERE a11 > 10`
Because JS implicitly converts strings to numbers when comparing them with integers, see https://www.w3schools.com/js/js_comparisons.asp
